// ═══════════════════════════════════════════════════════════════════════
//  AKKAMPARAMBIL FAMILY DATA — THE ONLY FILE YOU NEED TO EDIT
//
//  This file is used by ALL pages: home, members, tree, map, gallery.
//  Edit here → every page updates automatically.
//
//  HOW TO ADD A MEMBER:
//  Copy one entry below, paste it at the end of the array (before the ]),
//  fill in the details, make sure the id is a new unique number,
//  and set parentId / spouseId correctly.
//
//  parentId  = the id of their blood parent (father or mother)
//              set to null if they married INTO the family
//  spouseId  = the id of their husband/wife (set on BOTH people)
//              set to null if not married or spouse not listed
//  generation: 1 = grandparents, 2 = parents/aunts/uncles, 3 = cousins/children
// ═══════════════════════════════════════════════════════════════════════

const FAMILY_META = {
  name: "Akkamparambil",
  established: "Kerala, India",
  description: "A family rooted in Kerala, now spread across the world — connected by heritage, love, and memory."
};

const FAMILY_MEMBERS = [
  {
    id: 1,
    name: "Chacko Chacko Akkamparambil",
    nickname: "Great Great GrandFather",
    parentId: null,
    spouseId: 2,
    generation: 1,
    born: 1900,
    died: 1995,
    location: "Kuruppanthara, Kerala",
    country: "India",
    profession: "Entrepreneur",
    field: "Service",
    bio: "The patriarch of our family. Known for his wisdom and warmth.",
    photo: "",
    contact: { email: "", phone: "", whatsapp: "" }
  },
  {
    id: 2,
    name: "Annamma Chacko Akkamparambil",
    nickname: "Great Great GrandMother",
    parentId: null,
    spouseId: 1,
    generation: 1,
    born: 1905,
    died: 2000,
    location: "Kuruppanthara, Kerala",
    country: "India",
    profession: "Homemaker",
    field: "Homemaker",
    bio: "The heart of our family. Her love and cooking are legendary.",
    photo: "",
    contact: { email: "", phone: "", whatsapp: "" }
  },
{
    id: 3,
    name: "Kuriachan Chacko Akkamparambil",
    nickname: "Moolelachachan",
    parentId: 1,
    spouseId: 4,
    generation: 2,
    born: 1930,
    died: 1999,
    location: "Kuruppanthara, Kerala",
    country: "India",
    profession: "Entrepreneur",
    field: "Business",
    bio: "A Loving Father",
    photo: "Photos/Kuriachan.jpeg",
 },
 {
    id: 4,
    name: "Aliamma Kriachan Akkamparambil",
    nickname: "Moolelamma",
    parentId: null,
    spouseId: 3,
    generation: 2,
    born: 1940,
    died: 2010,
    location: "Kuruppanthara, Kerala",
    country: "India",
    profession: "Homemaker",
    field: "Homemaker",
    bio: "Dedicated nurse with 18 years of experience in ICU care.",
    photo: "Photos/Aliamma.jpeg",
    contact: { email: "", phone: "", whatsapp: "" }
  },
{
    id: 5,
    name: "Leesa Jose Akkamparambil",
    nickname: "Leesamma",
    parentId: 3,
    spouseId: 6,
    generation: 3,
    born: 1956,
    died: null,
    location: "Kuruppanthara, Kerala",
    country: "India",
    profession: "Entrepreneur",
    field: "business",
    bio: "Weaving Center Specialist",
    photo: "Photos/Leesa.jpeg",
    contact: { email: "", phone: "", whatsapp: "" }
  },
{
    id: 6,
    name: "P T Jose Akkamparambil",
    nickname: "Jose",
    parentId: null,
    spouseId: 5,
    generation: 3,
    born: 1948,
    died: 2009,
    location: "Kuruppanthara, Kerala",
    country: "India",
    profession: "Entrepreneur",
    field: "business",
    bio: "Weaving Center Specialist",
    photo: "Photos/Jose.jpeg",
    contact: { email: "", phone: "", whatsapp: "" }
  },
{
    id: 7,
    name: "Lijo Jose Akkamparambil",
    nickname: "Lijo",
    parentId: 5,
    spouseId: 8,
    generation: 4,
    born: 1975,
    died: null,
    location: "Kuruppanthara, Kerala",
    country: "India",
    profession: "Entrepreneur",
    field: "business",
    bio: "Weaving Center Specialist",
    photo: "Photos/Lijo.jpeg",
    contact: { email: "", phone: "", whatsapp: "" }
  },
  {
    id: 8,
    name: "Jossy Lijo Akkamparambil",
    nickname: "Jossy",
    parentId: null,
    spouseId: 7,
    generation: 4,
    born: 1976,
    died: null,
    location: "Kuruppanthara, Kerala",
    country: "India",
    profession: "Homemaker",
    field: "Homemaker",
    bio: "A Loving MoM",
    photo: "Photos/Jossy.jpeg",
    contact: { email: "", phone: "", whatsapp: "" }
  },
{
    id: 9,
    name: "Laiju Jose Akkamparambil",
    nickname: "Laiju",
    parentId: 5,
    spouseId: 10,
    generation: 4,
    born: 1978,
    died: null,
    location: "Italy, Italy",
    country: "Italy",
    profession: "Nurse",
    field: "Healthcare",
    bio: "A Loving Father",
    photo: "Photos/Laiju.jpeg",
    contact: { email: "", phone: "", whatsapp: "" }
  },
  {
    id: 10,
    name: "Jaimy Laiju Akkamparambil",
    nickname: "Jaime",
    parentId: null,
    spouseId: 9,
    generation: 4,
    born: 1979,
    died: null,
    location: "Kuruppanthara, Kerala",
    country: "India",
    profession: "Nurse",
    field: "Healthcare",
    bio: "A Loving MoM",
    photo: "Photos/Jaimy.jpeg",
    contact: { email: "", phone: "", whatsapp: "" }
  },
{
    id: 11,
    name: "Jisha Anil Thekkechirayil",
    nickname: "Jisha",
    parentId: 5,
    spouseId: 12,
    generation: 4,
    born: 1981,
    died: null,
    location: "Chicago, USA",
    country: "USA",
    profession: "Nurse",
    field: "Healthcare",
    bio: "A Loving MoM",
    photo: "Photos/Jisha.jpeg",
    contact: { email: "", phone: "", whatsapp: "" }
  },
  {
    id: 12,
    name: "Anil George Thekkechirayil",
    nickname: "Anil",
    parentId: null,
    spouseId: 11,
    generation: 4,
    born: 1980,
    died: null,
    location: "Chicago, USA",
    country: "USA",
    profession: "Entrepreneur",
    field: "Business",
    bio: "A Loving Father",
    photo: "Photos/Anil.jpeg",
    contact: { email: "", phone: "", whatsapp: "" }
  },
{
    id: 13,
    name: "Aleesha Anil Thekkechirayil",
    nickname: "Aleesha",
    parentId: 11,
    spouseId: null,
    generation: 5,
    born: 2005,
    died: null,
    location: "Chicago, USA",
    country: "USA",
    profession: "Student",
    field: "Education",
    bio: "A Loving Daughter",
    photo: "Photos/Aleesha.jpeg",
    contact: { email: "", phone: "", whatsapp: "" }
  },
  {
    id: 14,
    name: "Hannah Thekkechirayil",
    nickname: "Anil's Daughter",
    parentId: 11,
    spouseId: null,
    generation: 5,
    born: 2007,
    died: null,
    location: "Chicago, USA",
    country: "USA",
    profession: "Student",
    field: "Education",
    bio: "A Loving Daughter",
    photo: "Photos/Kid2.jpeg",
    contact: { email: "", phone: "", whatsapp: "" }
  },
{
    id: 15,
    name: "Anna Leesa Laiju",
    nickname: "Anna",
    parentId: 9,
    spouseId: null,
    generation: 5,
    born: 2005,
    died: null,
    location: "Italy, Italy",
    country: "Italy",
    profession: "Student",
    field: "Education",
    bio: "A Loving Daughter",
    photo: "Photos/Aleesha.jpeg",
    contact: { email: "", phone: "", whatsapp: "" }
  },
  {
    id: 16,
    name: "Angela Laiju",
    nickname: "Angela",
    parentId: 9,
    spouseId: null,
    generation: 5,
    born: 2010,
    died: null,
    location: "Italy, Italy",
    country: "Italy",
    profession: "Student",
    field: "Education",
    bio: "A Loving Daughter",
    photo: "Photos/Kid2.jpeg",
    contact: { email: "", phone: "", whatsapp: "" }
  },
{
    id: 17,
    name: "Anto Laiju",
    nickname: "Anto",
    parentId: 9,
    spouseId: null,
    generation: 5,
    born: 2017,
    died: null,
    location: "Italy, Italy",
    country: "Italy",
    profession: "Student",
    field: "Education",
    bio: "A Loving Daughter",
    photo: "Photos/Kid2.jpeg",
    contact: { email: "", phone: "", whatsapp: "" }
  },
  {
    id: 18,
    name: "Jose Lijo",
    nickname: "Jose",
    parentId: 7,
    spouseId: null,
    generation: 5,
    born: 2009,
    died: null,
    location: "Kuruppanthara, Kerala",
    country: "India",
    profession: "Student",
    field: "Education",
    bio: "A Loving Daughter",
    photo: "Photos/Kid2.jpeg",
    contact: { email: "", phone: "", whatsapp: "" }
  },
{
    id: 19,
    name: "Jessin Leesa Lijo",
    nickname: "Ammu",
    parentId: 7,
    spouseId: null,
    generation: 5,
    born: 2012,
    died: null,
    location: "Kuruppanthara, Kerala",
    country: "India",
    profession: "Student",
    field: "Education",
    bio: "A Loving Daughter",
    photo: "Photos/Kid2.jpeg",
    contact: { email: "", phone: "", whatsapp: "" }
  },
{
    id: 20,
    name: "Annakkutti Antony Naduvilapparambil",
    nickname: "Kochichechi",
    parentId: 1,
    spouseId: 21,
    generation: 2,
    born: 1940,
    died: null,
    location: "Aroor, Kerala",
    country: "India",
    profession: "Homemaker",
    field: "Homemaker",
    bio: "A Loving MoM",
    photo: "Photos/Kochichechi.jpeg",
    contact: { email: "jinto@example.com", phone: "+91-9876543210", whatsapp: "+91-9876543210" }
  },
  {
    id: 21,
    name: "Antony Naduvilapparambil",
    nickname: "Antony",
    parentId: null,
    spouseId: 20,
    generation: 2,
    born: 1935,
    died: 2012,
    location: "Aroor, Kerala",
    country: "India",
    profession: "Entrepreneur",
    field: "Business",
    bio: "A Loving Father",
    photo: "",
    contact: { email: "", phone: "", whatsapp: "" }
  },
{
    id: 22,
    name: "Leemon Antony Naduvilapparambil",
    nickname: "Lee",
    parentId: 20,
    spouseId: 23,
    generation: 3,
    born: 1935,
    died: null,
    location: "Aroor, Kerala",
    country: "India",
    profession: "Entrepreneur",
    field: "Business",
    bio: "A Loving Father",
    photo: "",
    contact: { email: "", phone: "", whatsapp: "" }
  },
{
    id: 23,
    name: "Ancy Leemon Naduvilapparambil",
    nickname: "Ancy",
    parentId: null,
    spouseId: 22,
    generation: 3,
    born: 1980,
    died: null,
    location: "Aroor, Kerala",
    country: "India",
    profession: "Teacher",
    field: "Education",
    bio: "A Loving MoM and Teacher",
    photo: "Photos/Ancy.jpeg",
    contact: { email: "jinto@example.com", phone: "+91-9876543210", whatsapp: "+91-9876543210" }
  },
{
    id: 24,
    name: "Benett Antony Naduvilapparambil",
    nickname: "Benett",
    parentId: 20,
    spouseId: 25,
    generation: 3,
    born: 1935,
    died: null,
    location: "Aroor, Kerala",
    country: "India",
    profession: "Entrepreneur",
    field: "Business",
    bio: "A Loving Father",
    photo: "",
    contact: { email: "", phone: "", whatsapp: "" }
  },
{
    id: 25,
    name: "Rekha Benett Naduvilapparambil",
    nickname: "Rekha",
    parentId: null,
    spouseId: 24,
    generation: 3,
    born: 1983,
    died: null,
    location: "Aroor, Kerala",
    country: "India",
    profession: "Homemaker",
    field: "Homemaker",
    bio: "A Loving MoM",
    photo: "Photos/Rekha.jpeg",
    contact: { email: "jinto@example.com", phone: "+91-9876543210", whatsapp: "+91-9876543210" }
  },
{
    id: 26,
    name: "Kid3 Antony Naduvilapparambil",
    nickname: "Kid3",
    parentId: 20,
    spouseId: null, //Sister-Nun
    generation: 3,
    born: 1980,
    died: null,
    location: "Aroor, Kerala",
    country: "India",
    profession: "Homemaker",
    field: "Homemaker",
    bio: "A Loving MoM",
    photo: "Photos/Rekha.jpeg",
    contact: { email: "jinto@example.com", phone: "+91-9876543210", whatsapp: "+91-9876543210" }
  },
{
    id: 27,
    name: "Kid4 Antony Naduvilapparambil",
    nickname: "Kid4",
    parentId: 20,
    spouseId: 28,
    generation: 3,
    born: 1983,
    died: null,
    location: "Aroor, Kerala",
    country: "India",
    profession: "Homemaker",
    field: "Homemaker",
    bio: "A Loving MoM",
    photo: "Photos/Rekha.jpeg",
    contact: { email: "jinto@example.com", phone: "+91-9876543210", whatsapp: "+91-9876543210" }
  },
{
    id: 28,
    name: "kid4 Antony Naduvilapparambil",
    nickname: "Kid4",
    parentId: null,
    spouseId: 27,
    generation: 3,
    born: 1983,
    died: null,
    location: "Aroor, Kerala",
    country: "India",
    profession: "Homemaker",
    field: "Homemaker",
    bio: "A Loving MoM",
    photo: "Photos/Rekha.jpeg",
    contact: { email: "jinto@example.com", phone: "+91-9876543210", whatsapp: "+91-9876543210" }
  },
  {
    id: 29,
    name: "AC Chacko Akkamparambil",
    nickname: "Jinto",
    parentId: 1,
    spouseId: 30,
    generation: 2,
    born: 1950,
    died: null,
    location: "Kuruppanthara, Kerala",
    country: "India",
    profession: "Service Sector",
    field: "Service",
    bio: "Built bridges — both literal and between family members.",
    photo: "Photos/acchacko.jpeg",
    contact: { email: "jinto@example.com", phone: "+91-9876543210", whatsapp: "+91-9876543210" }
  },
  {
    id: 30,
    name: "Mariamma Chacko Akkamparambil",
    nickname: "Kunjamma",
    parentId: null,
    spouseId: 29,
    generation: 2,
    born: 1955,
    died: 1999,
    location: "Kuruppanthara, Kerala",
    country: "India",
    profession: "Tailor",
    field: "Service",
    bio: "Dedicated educator, shaping young minds for over 20 years.",
    photo: "Photos/Mariamma.jpeg",
    contact: { email: "", phone: "", whatsapp: "" }
  },
  {
    id: 31,
    name: "Mathai Chacko Akkamparambil",
    nickname: "Kunjanja",
    parentId: 1,
    spouseId: 32,
    generation: 2,
    born: 1945,
    died: 2025,
    location: "Kuruppanthara, Kerala",
    country: "India",
    profession: "Service Sector",
    field: "Service",
    bio: "A loving Father",
    photo: "Photos/Mathai.jpeg",
    contact: { email: "rajan@example.com", phone: "", whatsapp: "" }
  },
  {
    id: 32,
    name: "Thressiamma Mathai Akkamparambil",
    nickname: "Kallarayamma",
    parentId: null,
    spouseId: 31,
    generation: 2,
    born: 1950,
    died: null,
    location: "Kuruppanthara, Kerala",
    country: "India",
    profession: "House Maker",
    field: "Home Maker",
    bio: "A loving Mother",
    photo: "",
    contact: { email: "", phone: "", whatsapp: "" }
  },
    {
    id: 33,
    name: "Joseph Chacko Akkamparambil",
    nickname: "Arun",
    parentId: 1,
    spouseId: 34,
    generation: 2,
    born: 1940,
    died: 2010,
    location: "Kuruppanthara, Kerala",
    country: "India",
    profession: "Business Student",
    field: "Business",
    bio: "Studying MBA at University of Toronto.",
    photo: "",
    contact: { email: "arun@example.com", phone: "", whatsapp: "" }
  },
  {
    id: 34,
    name: "Parelamma Akkamparambil",
    nickname: "Parelamma",
    parentId: null,
    spouseId: 33,
    generation: 2,
    born: 1945,
    died: null,
    location: "Kuruppanthara, Kerala",
    country: "India",
    profession: "Chartered Accountant",
    field: "Finance",
    bio: "CA with his own practice in East London.",
    photo: "",
    contact: { email: "balan@example.com", phone: "+44-7890123456", whatsapp: "+44-7890123456" }
  },
  {
    id: 35,
    name: "Kanjana Philip Munduvelil",
    nickname: "Kanjanamma",
    parentId: 1,
    spouseId: 36,
    generation: 2,
    born: 1978,
    died: null,
    location: "Peruva, Kerala",
    country: "India",
    profession: "Pharmacist",
    field: "Healthcare",
    bio: "Senior pharmacist at an NHS hospital in London.",
    photo: "",
    contact: { email: "", phone: "", whatsapp: "" }
  },
  {
    id: 36,
    name: "Philip Munduvelil",
    nickname: "Munduvelil",
    parentId: null,
    spouseId: 35,
    generation: 2,
    born: 2002,
    died: null,
    location: "Peruva, Kerala",
    country: "India",
    profession: "CS Student",
    field: "Engineering",
    bio: "Studying Computer Science at Imperial College London.",
    photo: "",
    contact: { email: "", phone: "", whatsapp: "" }
  },
  {
    id: 37,
    name: "Jinto Jacob Akkamparambil",
    nickname: "Jinto",
    parentId: 29,        // ✅ son of Jinto (id:3)
    spouseId: 38,
    generation: 3,
    born: 1983,
    died: null,
    location: "USA",
    country: "USA",
    profession: "IT Architect",
    field: "Technology",
    bio: "IT Architect",
    photo: "Photos/Jinto.jpeg",
    contact: { email: "", phone: "", whatsapp: "" }
  },
  {
    id: 38,
    name: "Remyamol Jinto Akkamparambil",
    nickname: "Remy",
    parentId: null,     // ✅ married in — NOT a child of id:3
    spouseId: 37,
    generation: 3,
    born: 1983,
    died: null,
    location: "USA",
    country: "USA",
    profession: "Nurse",
    field: "Healthcare",
    bio: "A loving Mom",
    photo: "Photos/Remya.jpeg",
    contact: { email: "", phone: "", whatsapp: "" }
  },{
    id: 39,
    name: "Ryan Jinto Akkamparambil",
    nickname: "Ponnus",
    parentId: 37,        // ✅ son of Jinto (id:3)
    spouseId: null,
    generation: 4,
    born: 2015,
    died: null,
    location: "USA",
    country: "USA",
    profession: "Student",
    field: "Education",
    bio: "A big time Soccer Fan",
    photo: "Photos/Ryan.jpeg",
    contact: { email: "", phone: "", whatsapp: "" }
  },
  {
    id: 40,
    name: "Jewel Jinto Akkamparambil",
    nickname: "Malus",
    parentId: 37,     // ✅ Daughter of Jinto
    spouseId: null,
    generation: 4,
    born: 2015,
    died: null,
    location: "USA",
    country: "USA",
    profession: "Student",
    field: "Education",
    bio: "Cute as Jewel",
    photo: "Photos/Jewel.jpeg",
    contact: { email: "", phone: "", whatsapp: "" }
  },
  {
    id: 41,
    name: "Jino Jacob Akkamparambil",
    nickname: "Jino",
    parentId: 29,        // ✅ son of Jinto (id:3)
    spouseId: 42,
    generation: 3,
    born: 1982,
    died: null,
    location: "Kuruppanthara, Kerala",
    country: "India",
    profession: "Real Estate",
    field: "Service",
    bio: "Real Estate",
    photo: "Photos/Jino.jpeg",
    contact: { email: "", phone: "", whatsapp: "" }
  },
  {
    id: 42,
    name: "Leena Jino Akkamparambil",
    nickname: "Leena",
    parentId: null,     // ✅ married in — NOT a child of id:3
    spouseId: 41,
    generation: 3,
    born: 1982,
    died: null,
    location: "Kuruppanthara, Kerala",
    country: "India",
    profession: "Bank Manager",
    field: "Finance",
    bio: "A Working MoM",
    photo: "Photos/Leena.jpeg",
    contact: { email: "", phone: "", whatsapp: "" }
  },{
    id: 43,
    name: "Sana Jino Akkamparambil",
    nickname: "Sana",
    parentId: 41,
    spouseId: null,
    generation: 4,
    born: 2013,
    died: null,
    location: "Kuruppanthara, Kerala",
    country: "India",
    profession: "Student",
    field: "Education",
    bio: "Cute as Sana",
    photo: "Photos/Sana.jpeg",
    contact: { email: "", phone: "", whatsapp: "" }
  },
  {
    id: 44,
    name: "Serah Jino Akkamparambil",
    nickname: "Serah",
    parentId: 41,     // ✅ Daughter of Jinto
    spouseId: null,
    generation: 4,
    born: 2014,
    died: null,
    location: "Kuruppanthara, Kerala",
    country: "India",
    profession: "Student",
    field: "Education",
    bio: "Cute as Serah",
    photo: "Photos/Serah.jpeg",
    contact: { email: "", phone: "", whatsapp: "" }
  },
  {
    id: 45,
    name: "Serena Jino Akkamparambil",
    nickname: "Serena",
    parentId: 41,     
    spouseId: null,
    generation: 4,
    born: 2016,
    died: null,
    location: "Kuruppanthara, Kerala",
    country: "India",
    profession: "Student",
    field: "Education",
    bio: "Cute as Serena",
    photo: "Photos/Serena.jpeg",
    contact: { email: "", phone: "", whatsapp: "" }
  },
  {
    id: 46,
    name: "Jeo Jacob Akkamparambil",
    nickname: "Jeo",
    parentId: 29,        
    spouseId: 47,
    generation: 3,
    born: 1989,
    died: null,
    location: "Ireland",
    country: "Ireland",
    profession: "Graphics",
    field: "Technology",
    bio: "Gaphics Genieus",
    photo: "Photos/Jeo.jpeg",
    contact: { email: "", phone: "", whatsapp: "" }
  },
  {
    id: 47,
    name: "Chinchu Jeo Akkamparambil",
    nickname: "Chinchu",
    parentId: null,
    spouseId: 46,
    generation: 3,
    born: 1990,
    died: null,
    location: "Ireland",
    country: "Ireland",
    profession: "Nurse",
    field: "Healthcare",
    bio: "A commmitted Nurse",
    photo: "Photos/Chinchu.jpeg",
    contact: { email: "", phone: "", whatsapp: "" }
  },
  {
    id: 48,
    name: "Mia Akkamparambil",
    nickname: "Mia",
    parentId: 46,        // ✅ son of Jinto (id:3)
    spouseId: null,
    generation: 4,
    born: 2016,
    died: null,
    location: "Ireland",
    country: "Ireland",
    profession: "Student",
    field: "Education",
    bio: "Cute as Mia",
    photo: "Photos/Mia.jpeg",
    contact: { email: "", phone: "", whatsapp: "" }
  },
  {
    id: 49,
    name: "Prince Philip Munduvelil",
    nickname: "Prince",
    parentId: 35,        // ✅ son of Jinto (id:3)
    spouseId: 50,
    generation: 3,
    born: 1981,
    died: null,
    location: "Peruva, Kerala",
    country: "India",
    profession: "Entrepreneur",
    field: "Business",
    bio: "Abcari :-)",
    photo: "Photos/Prince.jpeg",
    contact: { email: "", phone: "", whatsapp: "" }
  },
  
  {
    id: 51,
    name: "Jackson Joseph Akkamparambil",
    nickname: "Babuchettai",
    parentId: 33,        // ✅ son of Jinto (id:3)
    spouseId: 52,
    generation: 3,
    born: 1960,
    died: null,
    location: "Manama, Bahrain",
    country: "Behrain",
    profession: "Entrepreneur",
    field: "Business",
    bio: "A big shot",
    photo: "Photos/Jackson.jpeg",
    contact: { email: "", phone: "", whatsapp: "" }
  }
  // ── ADD NEW MEMBERS BELOW THIS LINE ──────────────────────────────
  // ,{
  //   id: 13,
  //   name: "New Person Name",
  //   nickname: "Nick",
  //   parentId: 3,       <- their parent's id
  //   spouseId: null,    <- spouse's id or null
  //   generation: 3,
  //   born: 1993,
  //   died: null,
  //   location: "City, State",
  //   country: "India",
  //   profession: "Doctor",
  //   field: "Medicine",
  //   bio: "Short description.",
  //   photo: "",
  //   contact: { email: "", phone: "", whatsapp: "" }
  // }
];
